import React, { useRef } from 'react';

import Head from 'next/head';

import { useRouter } from 'next/navigation';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const Home: React.FC = () => {
    const userIdRef = useRef<HTMLInputElement | null>(null);

    const router = useRouter();

    const handleClick = (): void => {
        const userId = userIdRef?.current?.value;

        if (userId != null) router.push(`cart-history/${userId}`);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={inter.className}>
                <label>
                    User Id: <input type="text" name="userId" ref={userIdRef} />
                </label>
                <button onClick={handleClick}>Go to Cart History</button>
            </main>
        </>
    );
};

export default Home;
